CREATE TABLE IF NOT EXISTS public.balances
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_date_time timestamp without time zone,
    last_modified_date timestamp without time zone,
    version bigint,
    amount bigint NOT NULL,
    balance_status character varying(255) COLLATE pg_catalog."default",
    bank_account bigint,
    CONSTRAINT balances_pkey PRIMARY KEY (id),
    CONSTRAINT fkl3lu400jd16fn6c19ok58usv6 FOREIGN KEY (bank_account)
    REFERENCES public.bank_accounts (id) MATCH SIMPLE
                                ON UPDATE NO ACTION
                                ON DELETE NO ACTION
)

CREATE TABLE IF NOT EXISTS public.bank
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_date_time timestamp without time zone,
    last_modified_date timestamp without time zone,
    version bigint,
    bank_name character varying(32) COLLATE pg_catalog."default" NOT NULL,
    phone character varying(32) COLLATE pg_catalog."default" NOT NULL,
    status character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT bank_pkey PRIMARY KEY (id),
    CONSTRAINT uk_bo8eaqt6psxcb30cmnd8ilppu UNIQUE (created_date_time),
    CONSTRAINT uk_k7b1fp39xemdvdtco9j7uk62y UNIQUE (bank_name)
    )

CREATE TABLE IF NOT EXISTS public.bank_accounts
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_date_time timestamp without time zone,
    last_modified_date timestamp without time zone,
    version bigint,
    account_number character varying(32) COLLATE pg_catalog."default" NOT NULL,
    password character varying(32) COLLATE pg_catalog."default" NOT NULL,
    account_status character varying(255) COLLATE pg_catalog."default",
    bank_id bigint,
    user_id bigint,
    CONSTRAINT bank_accounts_pkey PRIMARY KEY (id),
    CONSTRAINT uk_r9gi1et82prjsig51uqxj2qm6 UNIQUE (account_number),
    CONSTRAINT fkp1e4ss76i23o8kpwlackojsn3 FOREIGN KEY (bank_id)
    REFERENCES public.bank (id) MATCH SIMPLE
                                ON UPDATE NO ACTION
                                ON DELETE NO ACTION,
    CONSTRAINT fkrkt2vb002hro4k0rxfg1db67s FOREIGN KEY (user_id)
    REFERENCES public.profile (id) MATCH SIMPLE
                                ON UPDATE NO ACTION
                                ON DELETE NO ACTION
    )

CREATE TABLE IF NOT EXISTS public.payments
(
    id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    amount bigint,
    created_date timestamp without time zone,
    from_account bigint,
    to_account bigint,
    CONSTRAINT payments_pkey PRIMARY KEY (id),
    CONSTRAINT fkm5j8mfrtlhs6epeiph5v0k683 FOREIGN KEY (to_account)
    REFERENCES public.bank_accounts (id) MATCH SIMPLE
                           ON UPDATE NO ACTION
                           ON DELETE NO ACTION,
    CONSTRAINT fktlvi8swjad1jts2jmn0agncv8 FOREIGN KEY (from_account)
    REFERENCES public.bank_accounts (id) MATCH SIMPLE
                           ON UPDATE NO ACTION
                           ON DELETE NO ACTION
    )


CREATE TABLE IF NOT EXISTS public.profile
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_date_time timestamp without time zone,
    last_modified_date timestamp without time zone,
    version bigint,
    email character varying(32) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(32) COLLATE pg_catalog."default",
    login character varying(32) COLLATE pg_catalog."default" NOT NULL,
    password character varying(12) COLLATE pg_catalog."default" NOT NULL,
    profile_status character varying(32) COLLATE pg_catalog."default" NOT NULL,
    name character varying(32) COLLATE pg_catalog."default",
    profile_role character varying(12) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT profile_pkey PRIMARY KEY (id),
    CONSTRAINT uk_2f2ci7faksm3j03rrlgwv25c7 UNIQUE (created_date_time),
    CONSTRAINT uk_9d5dpsf2ufa6rjbi3y0elkdcd UNIQUE (email),
    CONSTRAINT uk_i5j9s35uyh2xe22wkhv1r2n8h UNIQUE (login)
    )

CREATE TABLE IF NOT EXISTS public.profile_history
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_date_time timestamp without time zone,
    last_modified_date timestamp without time zone,
    version bigint,
    email character varying(32) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(32) COLLATE pg_catalog."default",
    login character varying(32) COLLATE pg_catalog."default" NOT NULL,
    password character varying(12) COLLATE pg_catalog."default" NOT NULL,
    profile_status character varying COLLATE pg_catalog."default" NOT NULL,
    name character varying(32) COLLATE pg_catalog."default",
    CONSTRAINT profile_history_pkey PRIMARY KEY (id)
)